//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfChatPost
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatUser", Namespace="http://schemas.datacontract.org/2004/07/WcfChatPost")]
    public partial class ChatUser : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessage", Namespace="http://schemas.datacontract.org/2004/07/WcfChatPost")]
    public partial class ChatMessage : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private string MessageField;
        
        private WcfChatPost.ChatUser UserField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfChatPost.ChatUser User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatRoom", Namespace="http://schemas.datacontract.org/2004/07/WcfChatPost")]
    public partial class ChatRoom : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameRoomField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameRoom
        {
            get
            {
                return this.NameRoomField;
            }
            set
            {
                this.NameRoomField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IChatService", CallbackContract=typeof(IChatServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface IChatService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/ClientConnect", ReplyAction="http://tempuri.org/IChatService/ClientConnectResponse")]
    WcfChatPost.ChatUser ClientConnect(string userName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/ClientConnect", ReplyAction="http://tempuri.org/IChatService/ClientConnectResponse")]
    System.Threading.Tasks.Task<WcfChatPost.ChatUser> ClientConnectAsync(string userName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetAllUserss", ReplyAction="http://tempuri.org/IChatService/GetAllUserssResponse")]
    WcfChatPost.ChatUser[] GetAllUserss();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetAllUserss", ReplyAction="http://tempuri.org/IChatService/GetAllUserssResponse")]
    System.Threading.Tasks.Task<WcfChatPost.ChatUser[]> GetAllUserssAsync();
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendNewMessage")]
    void SendNewMessage(WcfChatPost.ChatMessage newMessage);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendNewMessage")]
    System.Threading.Tasks.Task SendNewMessageAsync(WcfChatPost.ChatMessage newMessage);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/RemoveUser")]
    void RemoveUser(WcfChatPost.ChatUser user);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/RemoveUser")]
    System.Threading.Tasks.Task RemoveUserAsync(WcfChatPost.ChatUser user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetNewMessagess", ReplyAction="http://tempuri.org/IChatService/GetNewMessagessResponse")]
    WcfChatPost.ChatMessage[] GetNewMessagess(WcfChatPost.ChatUser user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetNewMessagess", ReplyAction="http://tempuri.org/IChatService/GetNewMessagessResponse")]
    System.Threading.Tasks.Task<WcfChatPost.ChatMessage[]> GetNewMessagessAsync(WcfChatPost.ChatUser user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/CreateNewRoom", ReplyAction="http://tempuri.org/IChatService/CreateNewRoomResponse")]
    bool CreateNewRoom(WcfChatPost.ChatUser ourName, string[] users, WcfChatPost.ChatRoom nameRoom);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/CreateNewRoom", ReplyAction="http://tempuri.org/IChatService/CreateNewRoomResponse")]
    System.Threading.Tasks.Task<bool> CreateNewRoomAsync(WcfChatPost.ChatUser ourName, string[] users, WcfChatPost.ChatRoom nameRoom);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetRooms", ReplyAction="http://tempuri.org/IChatService/GetRoomsResponse")]
    WcfChatPost.ChatRoom[] GetRooms(WcfChatPost.ChatUser user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetRooms", ReplyAction="http://tempuri.org/IChatService/GetRoomsResponse")]
    System.Threading.Tasks.Task<WcfChatPost.ChatRoom[]> GetRoomsAsync(WcfChatPost.ChatUser user);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IChatServiceCallback
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/ConfirmUser", ReplyAction="http://tempuri.org/IChatService/ConfirmUserResponse")]
    bool ConfirmUser(WcfChatPost.ChatUser ourName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/CreateRoom", ReplyAction="http://tempuri.org/IChatService/CreateRoomResponse")]
    void CreateRoom(WcfChatPost.ChatUser ourName, WcfChatPost.ChatUser requiredName, WcfChatPost.ChatRoom nameRoom);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IChatServiceChannel : IChatService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ChatServiceClient : System.ServiceModel.DuplexClientBase<IChatService>, IChatService
{
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public WcfChatPost.ChatUser ClientConnect(string userName)
    {
        return base.Channel.ClientConnect(userName);
    }
    
    public System.Threading.Tasks.Task<WcfChatPost.ChatUser> ClientConnectAsync(string userName)
    {
        return base.Channel.ClientConnectAsync(userName);
    }
    
    public WcfChatPost.ChatUser[] GetAllUserss()
    {
        return base.Channel.GetAllUserss();
    }
    
    public System.Threading.Tasks.Task<WcfChatPost.ChatUser[]> GetAllUserssAsync()
    {
        return base.Channel.GetAllUserssAsync();
    }
    
    public void SendNewMessage(WcfChatPost.ChatMessage newMessage)
    {
        base.Channel.SendNewMessage(newMessage);
    }
    
    public System.Threading.Tasks.Task SendNewMessageAsync(WcfChatPost.ChatMessage newMessage)
    {
        return base.Channel.SendNewMessageAsync(newMessage);
    }
    
    public void RemoveUser(WcfChatPost.ChatUser user)
    {
        base.Channel.RemoveUser(user);
    }
    
    public System.Threading.Tasks.Task RemoveUserAsync(WcfChatPost.ChatUser user)
    {
        return base.Channel.RemoveUserAsync(user);
    }
    
    public WcfChatPost.ChatMessage[] GetNewMessagess(WcfChatPost.ChatUser user)
    {
        return base.Channel.GetNewMessagess(user);
    }
    
    public System.Threading.Tasks.Task<WcfChatPost.ChatMessage[]> GetNewMessagessAsync(WcfChatPost.ChatUser user)
    {
        return base.Channel.GetNewMessagessAsync(user);
    }
    
    public bool CreateNewRoom(WcfChatPost.ChatUser ourName, string[] users, WcfChatPost.ChatRoom nameRoom)
    {
        return base.Channel.CreateNewRoom(ourName, users, nameRoom);
    }
    
    public System.Threading.Tasks.Task<bool> CreateNewRoomAsync(WcfChatPost.ChatUser ourName, string[] users, WcfChatPost.ChatRoom nameRoom)
    {
        return base.Channel.CreateNewRoomAsync(ourName, users, nameRoom);
    }
    
    public WcfChatPost.ChatRoom[] GetRooms(WcfChatPost.ChatUser user)
    {
        return base.Channel.GetRooms(user);
    }
    
    public System.Threading.Tasks.Task<WcfChatPost.ChatRoom[]> GetRoomsAsync(WcfChatPost.ChatUser user)
    {
        return base.Channel.GetRoomsAsync(user);
    }
}
