//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatClient.ServiceReference3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatUser", Namespace="http://schemas.datacontract.org/2004/07/WcfChatPost")]
    [System.SerializableAttribute()]
    public partial class ChatUser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessage", Namespace="http://schemas.datacontract.org/2004/07/WcfChatPost")]
    [System.SerializableAttribute()]
    public partial class ChatMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ChatClient.ServiceReference3.ChatUser UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ChatClient.ServiceReference3.ChatUser User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatRoom", Namespace="http://schemas.datacontract.org/2004/07/WcfChatPost")]
    [System.SerializableAttribute()]
    public partial class ChatRoom : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameRoomField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameRoom {
            get {
                return this.NameRoomField;
            }
            set {
                if ((object.ReferenceEquals(this.NameRoomField, value) != true)) {
                    this.NameRoomField = value;
                    this.RaisePropertyChanged("NameRoom");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.IChatService", CallbackContract=typeof(ChatClient.ServiceReference3.IChatServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IChatService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/ClientConnect", ReplyAction="http://tempuri.org/IChatService/ClientConnectResponse")]
        ChatClient.ServiceReference3.ChatUser ClientConnect(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/ClientConnect", ReplyAction="http://tempuri.org/IChatService/ClientConnectResponse")]
        System.Threading.Tasks.Task<ChatClient.ServiceReference3.ChatUser> ClientConnectAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetAllUserss", ReplyAction="http://tempuri.org/IChatService/GetAllUserssResponse")]
        ChatClient.ServiceReference3.ChatUser[] GetAllUserss();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetAllUserss", ReplyAction="http://tempuri.org/IChatService/GetAllUserssResponse")]
        System.Threading.Tasks.Task<ChatClient.ServiceReference3.ChatUser[]> GetAllUserssAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendNewMessage")]
        void SendNewMessage(ChatClient.ServiceReference3.ChatMessage newMessage);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendNewMessage")]
        System.Threading.Tasks.Task SendNewMessageAsync(ChatClient.ServiceReference3.ChatMessage newMessage);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/RemoveUser")]
        void RemoveUser(ChatClient.ServiceReference3.ChatUser user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/RemoveUser")]
        System.Threading.Tasks.Task RemoveUserAsync(ChatClient.ServiceReference3.ChatUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetNewMessagess", ReplyAction="http://tempuri.org/IChatService/GetNewMessagessResponse")]
        ChatClient.ServiceReference3.ChatMessage[] GetNewMessagess(ChatClient.ServiceReference3.ChatUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetNewMessagess", ReplyAction="http://tempuri.org/IChatService/GetNewMessagessResponse")]
        System.Threading.Tasks.Task<ChatClient.ServiceReference3.ChatMessage[]> GetNewMessagessAsync(ChatClient.ServiceReference3.ChatUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/CreateNewRoom", ReplyAction="http://tempuri.org/IChatService/CreateNewRoomResponse")]
        bool CreateNewRoom(ChatClient.ServiceReference3.ChatUser ourName, string[] users, ChatClient.ServiceReference3.ChatRoom nameRoom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/CreateNewRoom", ReplyAction="http://tempuri.org/IChatService/CreateNewRoomResponse")]
        System.Threading.Tasks.Task<bool> CreateNewRoomAsync(ChatClient.ServiceReference3.ChatUser ourName, string[] users, ChatClient.ServiceReference3.ChatRoom nameRoom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetRooms", ReplyAction="http://tempuri.org/IChatService/GetRoomsResponse")]
        ChatClient.ServiceReference3.ChatRoom[] GetRooms(ChatClient.ServiceReference3.ChatUser user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/GetRooms", ReplyAction="http://tempuri.org/IChatService/GetRoomsResponse")]
        System.Threading.Tasks.Task<ChatClient.ServiceReference3.ChatRoom[]> GetRoomsAsync(ChatClient.ServiceReference3.ChatUser user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatService/ConfirmUser", ReplyAction="http://tempuri.org/IChatService/ConfirmUserResponse")]
        bool ConfirmUser(ChatClient.ServiceReference3.ChatUser ourName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/CreateRoom")]
        void CreateRoom(ChatClient.ServiceReference3.ChatUser ourName, ChatClient.ServiceReference3.ChatUser requiredName, ChatClient.ServiceReference3.ChatRoom nameRoom);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceChannel : ChatClient.ServiceReference3.IChatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatServiceClient : System.ServiceModel.DuplexClientBase<ChatClient.ServiceReference3.IChatService>, ChatClient.ServiceReference3.IChatService {
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public ChatClient.ServiceReference3.ChatUser ClientConnect(string userName) {
            return base.Channel.ClientConnect(userName);
        }
        
        public System.Threading.Tasks.Task<ChatClient.ServiceReference3.ChatUser> ClientConnectAsync(string userName) {
            return base.Channel.ClientConnectAsync(userName);
        }
        
        public ChatClient.ServiceReference3.ChatUser[] GetAllUserss() {
            return base.Channel.GetAllUserss();
        }
        
        public System.Threading.Tasks.Task<ChatClient.ServiceReference3.ChatUser[]> GetAllUserssAsync() {
            return base.Channel.GetAllUserssAsync();
        }
        
        public void SendNewMessage(ChatClient.ServiceReference3.ChatMessage newMessage) {
            base.Channel.SendNewMessage(newMessage);
        }
        
        public System.Threading.Tasks.Task SendNewMessageAsync(ChatClient.ServiceReference3.ChatMessage newMessage) {
            return base.Channel.SendNewMessageAsync(newMessage);
        }
        
        public void RemoveUser(ChatClient.ServiceReference3.ChatUser user) {
            base.Channel.RemoveUser(user);
        }
        
        public System.Threading.Tasks.Task RemoveUserAsync(ChatClient.ServiceReference3.ChatUser user) {
            return base.Channel.RemoveUserAsync(user);
        }
        
        public ChatClient.ServiceReference3.ChatMessage[] GetNewMessagess(ChatClient.ServiceReference3.ChatUser user) {
            return base.Channel.GetNewMessagess(user);
        }
        
        public System.Threading.Tasks.Task<ChatClient.ServiceReference3.ChatMessage[]> GetNewMessagessAsync(ChatClient.ServiceReference3.ChatUser user) {
            return base.Channel.GetNewMessagessAsync(user);
        }
        
        public bool CreateNewRoom(ChatClient.ServiceReference3.ChatUser ourName, string[] users, ChatClient.ServiceReference3.ChatRoom nameRoom) {
            return base.Channel.CreateNewRoom(ourName, users, nameRoom);
        }
        
        public System.Threading.Tasks.Task<bool> CreateNewRoomAsync(ChatClient.ServiceReference3.ChatUser ourName, string[] users, ChatClient.ServiceReference3.ChatRoom nameRoom) {
            return base.Channel.CreateNewRoomAsync(ourName, users, nameRoom);
        }
        
        public ChatClient.ServiceReference3.ChatRoom[] GetRooms(ChatClient.ServiceReference3.ChatUser user) {
            return base.Channel.GetRooms(user);
        }
        
        public System.Threading.Tasks.Task<ChatClient.ServiceReference3.ChatRoom[]> GetRoomsAsync(ChatClient.ServiceReference3.ChatUser user) {
            return base.Channel.GetRoomsAsync(user);
        }
    }
}
